### ISSUE TITLE
Make support for Sass optional

### ISSUE THREAD

**Issue by tommmyy** [lundegaard/react-union#120]
Today I think sass support is not needed anymore. 
On the other hand, we lack the support of CSS modules and CSS 4 syntax.

There are two options I see:

1) Drop Sass the support entirely and write a tutorial about how to add it manually.
2) Make Sass support optional and write lots of `if`s in our code to make it conditional.  Than make sass-loader and node-sass dependencies optional in our `package.json`

**Comment by tommmyy** [comment]
@aizerin @wafflepie I would like to see your feedback.

**Comment by wafflepie** [comment]
I agree with dropping SCSS support entirely and replacing it with something like cssnext. Let's just explicitly support a single way of styling React components and focus on making it as seamless as possible.

The only other (React-specific) real alternative is CSS-in-JS (styled-components, Glamorous, you name it) which doesn't really stand in the way of supporting cssnext.

**Comment by aizerin** [comment]
I'm for option 1. And I wouldn't add support for cssnex or any other css processor. If somebody wants it, it is possible to merge it via union.config. We should not make another react-create-app with ultra webpack config.

**Comment by wafflepie** [comment]
Sure, that's another possible option. I would also like to see how difficult would it be to add a preprocessor using our `mergeWebpackConfig` solution (and whether there would be any gotchas). Maybe using something like https://github.com/neutrinojs/webpack-chain would be useful. What do you think? `mergeWebpackConfig` is powerful, but not very clean and not comfortable to use IMO.

To be honest, create-react-app's webpack config complexity is due to their ejection mechanism, lots of comments and backwards compatibility. I don't see how it's an "ultra webpack config", it just supports everything you need for developing web applications without the need to do any manual configuration, which is good.

**Comment by tommmyy** [comment]
@wafflepie It is about modular configuration we are discussing for v1.0.0. We just need to ssr branch to be ready.

**Comment by aizerin** [comment]
@wafflepie with `mergeWebpackConfig` is easy to merge anything, you can do it manually or use webpack-merge or whatever.

I can see a problem with supporting everything you need for developing. Because someone can need node-sass and someone else cssnext. We need modularity for that.
