### ISSUE TITLE
[react-union] Suggestion – use the data-union-widget attribute value

### ISSUE THREAD

**Issue by wafflepie** [lundegaard/react-union#8]
Currently:
```
<script data-union-widget="" type="application/json">
{
	"name": "my-widget",
	"container": "my-widget-root",
	"namespace": "unique-string"
}
</script>
```
My suggestion:
```
<script data-union-widget="my-widget" type="application/json">
{
	"container": "my-widget-root",
	"namespace": "unique-string"
}
</script>
```
I think that (strictly semantically) this makes more sense that the current version. What do you think? Would the change make it more harder to generate the mark-up?

**Comment by tommmyy** [comment]
I have wondered about it too.. but in the version above you divide information about widget into two places. That is just one con. But pro is here:

```
// that should also work
<script data-union-widget="my-widget" type="application/json"></script>
```

We can even provide 2 ways to define dom-mark... data-attributes AND json... 
So that should also work:

```
<script data-union-widget="my-widget" data-union-namespace="ns1" type="application/json">
{
  data: {/* some initial data, better to use JSON format */}
}
</script>
```

And ultimately:

```
<script data-union-widget="my-widget" data-union-namespace="ns1" type="application/json">
{/* some initial data, better to use JSON format */}
</script>
```
I think last one is best.

**Comment by wafflepie** [comment]
I like the last one best as well!
